import { MD3LightTheme, MD3DarkTheme } from 'react-native-paper';

export const theme = {
  ...MD3LightTheme,
  colors: {
    ...MD3LightTheme.colors,
    primary: '#000000',
    background: '#ffffff',
    surface: '#ffffff',
    surfaceVariant: '#f5f5f5',
    onSurface: '#000000',
    onSurfaceVariant: '#666666',
    outline: '#e0e0e0',
    outlineVariant: '#f0f0f0',
    inverseSurface: '#121212',
    inverseOnSurface: '#ffffff',
    primaryContainer: '#f0f0f0',
    onPrimaryContainer: '#000000',
    secondary: '#666666',
    onSecondary: '#ffffff',
    tertiary: '#333333',
    onTertiary: '#ffffff',
    error: '#dc2626',
    onError: '#ffffff',
    errorContainer: '#fef2f2',
    onErrorContainer: '#dc2626',
    // Chat-specific colors
    userMessage: '#000000',
    assistantMessage: '#f5f5f5',
    inputBackground: '#f9f9f9',
    border: '#e0e0e0',
    muted: '#9ca3af',
    mutedForeground: '#6b7280',
    accent: '#f3f4f6',
    accentForeground: '#1f2937',
    destructive: '#dc2626',
    destructiveForeground: '#ffffff',
  },
};

export const darkTheme = {
  ...MD3DarkTheme,
  colors: {
    ...MD3DarkTheme.colors,
    primary: '#ffffff',
    background: '#0a0a0a',
    surface: '#0a0a0a',
    surfaceVariant: '#1a1a1a',
    onSurface: '#ffffff',
    onSurfaceVariant: '#a1a1aa',
    outline: '#27272a',
    outlineVariant: '#18181b',
    inverseSurface: '#ffffff',
    inverseOnSurface: '#000000',
    primaryContainer: '#1a1a1a',
    onPrimaryContainer: '#ffffff',
    secondary: '#a1a1aa',
    onSecondary: '#000000',
    tertiary: '#d4d4d8',
    onTertiary: '#000000',
    error: '#dc2626',
    onError: '#ffffff',
    errorContainer: '#450a0a',
    onErrorContainer: '#fca5a5',
    // Chat-specific colors
    userMessage: '#ffffff',
    assistantMessage: '#1a1a1a',
    inputBackground: '#18181b',
    border: '#27272a',
    muted: '#6b7280',
    mutedForeground: '#9ca3af',
    accent: '#18181b',
    accentForeground: '#f9fafb',
    destructive: '#dc2626',
    destructiveForeground: '#ffffff',
  },
};